# WILL OF THE CITY :: THE INDEX  —  foot
font=Perfect DOS VGA 437:size=12
dpi-aware=no
pad=14x14
[cursor]
style=block
color=05080d 5DADE2
[colors]
alpha=0.94
background=05080d
foreground=85C5E8
regular0=05080d
regular1=FF6B6B
regular2=5DE285
regular3=85C5E8
regular4=5DADE2
regular5=3A7CA5
regular6=5DADE2
regular7=85C5E8
bright0=3A7CA5
bright1=FF6B6B
bright2=5DE285
bright3=85C5E8
bright4=5DADE2
bright5=3A7CA5
bright6=85C5E8
bright7=FFFFFF
[main]
